"""add favorite_genre to users

Revision ID: 1e6075556af0
Revises: 
Create Date: 2026-03-31 08:55:15.638335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6075556af0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_genre', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_favorite_genre'), 'users', ['favorite_genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_favorite_genre'), table_name='users')
    op.drop_column('users', 'favorite_genre')
    # ### end Alembic commands ###
